#!/bin/bash

UPTIME=$(</proc/uptime)
UPTIME=${UPTIME%%.*}

if [[ -z $UPTIMELIMIT ]]; then
  UPTIMELIMIT=1800;
fi
if [[ $UPTIME -lt $UPTIMELIMIT ]]; then
  echo "uptime $UPTIME < $UPTIMELIMIT";
  exit 1;
fi
