#!/bin/bash

GREP="";
function grep_process() {
  OUT=$(ps ax -o cmd|grep "/$GREP "|grep -v grep);
   if [[ ! -z "$OUT" ]]; then
    echo $OUT;
    echo $GREP | xargs;
    exit 1;
  fi
}

GREP="apt";
grep_process;

GREP="cp";
grep_process;

GREP="dpkg";
grep_process;

GREP="mv";
grep_process;

GREP="rm";
grep_process;

GREP="rsync";
grep_process;

GREP="wget";
grep_process;
