#!/bin/bash

GREP="";
PSAXCMD=$(ps ax -o cmd);
function grep_process() {
  OUT=$(echo "$PSAXCMD"|grep -E "(^|/)$GREP( |$)"|grep -v grep);
  if [[ ! -z "$OUT" ]]; then
    echo "$GREP" | xargs;
    exit 1;
  fi
}

if [[ -z $MAINBASENAME ]]; then
  MAINBASENAME="autooff";
fi

if [[ -f "/etc/dptools/$MAINBASENAME.processes" ]]; then
  source "/etc/dptools/$MAINBASENAME.processes";
fi

GREP="apt";
grep_process;

GREP="cfdisk";
grep_process;

GREP="cp";
grep_process;

GREP="dd";
grep_process;

GREP="dpkg";
grep_process;

GREP="fdisk";
grep_process;

GREP="gparted";
grep_process;

GREP="gpartedbin";
grep_process;

GREP="httrack";
grep_process;

GREP="lftp";
grep_process;

GREP="md5deep";
grep_process;

GREP="mv";
grep_process;

GREP="pacman";
grep_process;

GREP="parted";
grep_process;

GREP="rm";
grep_process;

GREP="rsync";
grep_process;

GREP="sgdisk";
grep_process;

GREP="scp";
grep_process;

# GREP="screen";
# grep_process;

GREP="tar";
grep_process;

GREP="wget";
grep_process;

GREP="yum";
grep_process;
