#!/bin/bash

command -v smbstatus > /dev/null;
if [[ $? -eq 0 ]]; then
  SMB=$(smbstatus --shares|grep -v "^IPC\\\$[[:space:]]\+[0-9]\+.*$"|grep -v "^Service[[:space:]]\+pid.*$"|grep -v "^\-\-\-\+.*$"|xargs 2>&1)
  if [[ ! -z "$SMB" ]]; then
    echo $SMB | tr '\n' ' ';
    exit 1;
  fi
else
  exit 0;
fi
