#!/bin/bash

command -v zpool  &> /dev/null;
if [[ $? -ne 0 ]]; then
  exit 0;
fi

zpool status|grep -zqv "currently being resilvered" > /dev/null;
if [[ $? -ne 0 ]]; then
  echo 'zfs resilver';
  exit 1;
else
  exit 0;
fi

zpool status|grep -zqv "scrub in progress" > /dev/null;
if [[ $? -ne 0 ]]; then
  echo 'zfs scrub';
  exit 1;
else
  exit 0;
fi
